name:                ad
version:             0.1.0.0
github:              "codei/ad-for-dp"
license:             BSD3
author:              "TANIGUCHI Kohei"
maintainer:          "a.d.xvii.kal.mai@gmail.com"
copyright:           "2018 TANIGUCHI Kohei"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/ad#readme>

dependencies:
  - base >= 4.7 && < 5
  - CC-delcont

executable:
  main: Main.hs
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  ad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
